### ISSUE TITLE
最近好像新增了反扒机制？

### ISSUE THREAD

**Issue by shuxp** [merelysmile/Scrapy_Boss#1]
我试了你的代码，parse的response一直为空，是不是新加了反扒机制呢？

**Comment by merelysmile** [comment]
感谢指出，我在外面，具体问题只能周日晚上回去了再看，对于response为空的情况，我猜测你在运行run.py时城市参数会不会是填错了或者不规范，导致匹配不上，我的代码没有妥善的容错性。

**Comment by shuxp** [comment]
我查了下，应该是重定向问题，boss搞了个ka.js，目测是防爬的，这个我搞不定。。

**Comment by merelysmile** [comment]
好的，之后我试一试。我一直觉得这种网站都不需要反爬的，毕竟最多展示500条数据已经是种很残忍的反爬了😂

**Comment by merelysmile** [comment]
> 我查了下，应该是重定向问题，老板搞了个ka.js，目测是防爬的，这个我搞不定..

你好朋友，直聘网现在确实会重定向了，需要在请求的时候携带cookie。因此有两个思路，可以先模拟登录然后携带cookie访问，或者简单点可以将浏览器开发工具里的cookie复制到settings.py里的请求头headers中，同时设置COOKIES_ENABLED = False就好了。

**Comment by shuxp** [comment]
> > 我查了下，应该是重定向问题，老板搞了个ka.js，目测是防爬的，这个我搞不定..
> 
> 你好朋友，直聘网现在确实会重定向了，需要在请求的时候携带cookie。我有两个思路，可以先模拟登录然后携带cookie访问，或者简单点可以将浏览器开发工具里的cookie复制到settings.py里的请求头headers中，同时设置COOKIES_ENABLED = False就好了。

厉害，我试下，谢谢~
